### ISSUE TITLE
`abbreviations` isn't defined in the typescript definition file

### ISSUE THREAD

**Issue by stkrzysiak** [vvo/tzdb#255]
When running node version 14.x the lack of typescript definition causes an error, but this doesn't happen in node v16.x. Not sure exactly why but will PR the fix.

```
➜  node-vanilla node index.js                                                          
xxxxxx/node-vanilla/index.js:1
import { abbreviations } from '@vvo/tzdb';
         ^^^^^^^^^^^^^
SyntaxError: The requested module '@vvo/tzdb' does not provide an export named 'abbreviations'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
➜  node-vanilla nvm use v16.0.0
Now using node v16.0.0 (npm v7.10.0)
➜  node-vanilla node index.js  
ACT
```

index.js: 

```
import { abbreviations } from '@vvo/tzdb';
console.log(abbreviations[Object.keys(abbreviations)[0]]);
```

**Comment by stkrzysiak** [comment]
PR up, not sure why it didn't link up, build failing but vercel gives me a 404.  #256

**Comment by BenceSzalai** [comment]
Hi! TypeScript TSC gives me `TS2305: Module '"@vvo/tzdb"' has no exported member 'abbreviations'.`

Is there a reason for the abbreviations to not be in `index.d.ts`? Or more precisely do we know why #256 is failing?

**Comment by stkrzysiak** [comment]
I forgot about this issue entirely, can you provide me steps to reproduce what you're seeing @BenceSzalai

**Comment by BenceSzalai** [comment]
In my setup simply making a new TypeScript file anywhere with the following triggers the issue:
```ts
import { abbreviations } from '@vvo/tzdb'
```

Right now my workaround is to add a definition manually before the import like this:
```ts
declare module '@vvo/tzdb' {
  export const abbreviations: Record<string, string>
}
```
